
[Shipwrecks]
	#
	# How rare are End Shipwreck in End Highlands biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	endShipwreckSpawnrate = 15
	#
	# Add the ID/resource location of the biome you don't want
	# RS's shipwrecks to spawn in. Separate each ID with a comma ,
	#
	#Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
	blacklistedShipwreckBiomes = ""
	#
	# Add End Shipwreck to modded End biomes.
	addEndShipwreckToModdedBiomes = true

